# Generated by Django 3.0.8 on 2020-07-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='страна')),
            ],
        ),
        migrations.CreateModel(
            name='Hot_room',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('roomnum', models.PositiveSmallIntegerField(unique=True, verbose_name='номер комнаты')),
                ('roomtype', models.CharField(choices=[('', ''), ('DLT', 'DL Tween'), ('DLK', 'DL King'), ('EXS', 'EXS'), ('JST', 'JST'), ('PS', 'PS'), ('TRP', 'Triple'), ('DIS', 'DISABLE')], default='', max_length=8, verbose_name='тип комнаты')),
                ('floor', models.PositiveSmallIntegerField(verbose_name='этаж')),
                ('orderby', models.PositiveSmallIntegerField(verbose_name='расположение комнат')),
                ('view', models.CharField(max_length=50, verbose_name='обзор')),
                ('colored', models.CharField(choices=[('dff0d8', 'Nut'), ('fcf8e3', 'Wood'), ('f2dede', 'Pink'), ('5cb85c', 'Green'), ('ffffff', 'White')], default='dff0d8', max_length=10, verbose_name='цвет')),
                ('reserved', models.DateField(verbose_name='дата резервирования')),
                ('status', models.CharField(choices=[('repair', 'ремонт'), ('free', 'свободный'), ('busy', 'занятый'), ('dirty', 'грязный')], max_length=10, verbose_name='состояние')),
                ('remark', models.CharField(max_length=300, verbose_name='примечание')),
            ],
        ),
        migrations.CreateModel(
            name='Hot_guest',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('passportnum', models.CharField(max_length=25, unique=True, verbose_name='№ паспорта')),
                ('surname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('birthdate', models.DateField(verbose_name='дата рождения')),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE')], default='female', max_length=8, verbose_name='пол')),
                ('typeofvisa', models.CharField(choices=[('sp', 'SP'), ('bs', 'BS'), ('of', 'OF'), ('wp', 'WP'), ('pr', 'PR'), ('dp', 'DP'), ('nn', 'NO NEED')], default='nn', max_length=10, verbose_name='тип визы')),
                ('company', models.CharField(max_length=50, verbose_name='компания')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('fk_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Country', verbose_name='страна')),
            ],
        ),
        migrations.CreateModel(
            name='Hot_book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('arrdate', models.DateTimeField(verbose_name='дата прибытия')),
                ('depdate', models.DateTimeField(verbose_name='дата убытия')),
                ('paymethod', models.PositiveSmallIntegerField(verbose_name='сумма оплаты')),
                ('payrate', models.CharField(choices=[('cash', 'CASH'), ('visa', 'VISA'), ('cl', 'CL'), ('poa', 'POA'), ('all_cl', 'All Cl')], default='cash', max_length=8, verbose_name='оплата')),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('dtm', 'DTM')], default='usd', max_length=4, verbose_name='курс оплаты')),
                ('active', models.BooleanField(default=True, verbose_name='')),
                ('fk_gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Hot_guest', verbose_name='постоялец')),
                ('fk_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Hot_room', verbose_name='номер комнаты')),
            ],
        ),
    ]
